### ISSUE TITLE
Specify operating system

### ISSUE THREAD

**Issue by paulomcnally** [takinbo/docker-kannel#1]
- Change you're repo name to docker-kannel-ubuntu
- Add instructions

:+1:

**Comment by takinbo** [comment]
Thanks for logging this issue. Not sure though why I should rename the repo name. I'll update the repo with instructions later.

**Comment by paulomcnally** [comment]
You should post your excellent contribution

I forget the name, but you should write the documentation used ubuntu

**Comment by takinbo** [comment]
@paulomcnally I have updated the documentation and contributed it to the docker index. You'll find it here - https://registry.hub.docker.com/u/timbaobjects/kannel/

**Comment by paulomcnally** [comment]
:+1:
