### ISSUE TITLE
Run commands don't work

### ISSUE THREAD

**Issue by oren4322** [takinbo/docker-kannel#2]
Getting message of Unable to find image 'kannel:latest' locally

Even when supplying the right image then getting:

"ERROR: fopen failed: couldn't open `/etc/kannel/kannel.conf'"

**Comment by takinbo** [comment]
There are two issues here:
1. You either need to build this image first or download it from docker hub. You can easily get the image from docker hub by running: docker pull takinbo/kannel and then replace every instance of the image name (kannel) with takinbo/kannel. E.g. `docker run --rm -t -i --name bearerbox --hostname bearerbox --volume /opt/kannel/etc/:/etc/kannel --volume /opt/kannel/log:/var/log/kannel --volume /opt/kannel/spool:/var/spool/kannel takinbo/kannel bearerbox -v 0 /etc/kannel/kannel.conf`
2. You will need to map an existing directory containing your kannel.conf file to the /etc/kannel directory on the container. I have used /opt/kannel in my example.

**Comment by oren4322** [comment]
The bearerbox started, but the smsbox fails with the following error:

2015-03-08 20:49:32 [1] [0] DEBUG: Connecting to <192.168.59.103>
2015-03-08 20:49:32 [1] [0] INFO: Connected to bearerbox at 192.168.59.103
port 13001.
2015-03-08 20:49:32 [1] [0] DEBUG: Started thread 8
(gw/heartbeat.c:heartbeat_thread)
2015-03-08 20:49:32 [1] [8] DEBUG: Thread 8
(gw/heartbeat.c:heartbeat_thread) maps to pid 1.
2015-03-08 20:49:32 [1] [0] ERROR: Connection closed by the bearerbox.
2015-03-08 20:49:32 [1] [0] ERROR: Bearerbox is gone, restarting
2015-03-08 20:49:32 [1] [0] INFO: Received (and handled?) 0 requests in 0
seconds (-nan per second)
2015-03-08 20:49:32 [1] [0] INFO: Kannel smsbox terminating.
2015-03-08 20:49:32 [1] [8] DEBUG: Thread 8
(gw/heartbeat.c:heartbeat_thread) terminates.
2015-03-08 20:49:32 [1] [0] DEBUG: Waiting for 2
(gwlib/http.c:server_thread) to terminate

Took the kannel.conf from
http://www.kannel.org/download/1.5.0/gateway-1.5.0/gw/smskannel.conf and
only changed the 127.0.0.1 to 192.168.59.103 (docker's), also exposed ports.
What could be wrong?

2015-03-08 2:29 GMT+02:00 Tim Akinbo notifications@github.com:

> There are two issues here:
> 1. You either need to build this image first or download it from
>    docker hub. You can easily get the image from docker hub by running: docker
>    pull takinbo/kannel and then replace every instance of the image name
>    (kannel) with takinbo/kannel. E.g. docker run --rm -t -i --name
>    bearerbox --hostname bearerbox --volume /opt/kannel/etc/:/etc/kannel
>    --volume /opt/kannel/log:/var/log/kannel --volume
>    /opt/kannel/spool:/var/spool/kannel takinbo/kannel bearerbox -v 0
>    /etc/kannel/kannel.conf
> 2. You will need to map an existing directory containing your
>    kannel.conf file to the /etc/kannel directory on the container. I have used
>    /opt/kannel in my example.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/takinbo/docker-kannel/issues/2#issuecomment-77724927.

## 

Yaniv Oren
_Email:_ oren432@gmail.com
_Phone:_ 972 508 612502
_Site:_ www.Teach.Watch

**Comment by oren4322** [comment]
Tim,
Are you familiar with this error?
Can you supply your kannel.conf?

2015-03-08 22:52 GMT+02:00 יניב אורן oren432@gmail.com:

> The bearerbox started, but the smsbox fails with the following error:
> 
> 2015-03-08 20:49:32 [1] [0] DEBUG: Connecting to <192.168.59.103>
> 2015-03-08 20:49:32 [1] [0] INFO: Connected to bearerbox at 192.168.59.103
> port 13001.
> 2015-03-08 20:49:32 [1] [0] DEBUG: Started thread 8
> (gw/heartbeat.c:heartbeat_thread)
> 2015-03-08 20:49:32 [1] [8] DEBUG: Thread 8
> (gw/heartbeat.c:heartbeat_thread) maps to pid 1.
> 2015-03-08 20:49:32 [1] [0] ERROR: Connection closed by the bearerbox.
> 2015-03-08 20:49:32 [1] [0] ERROR: Bearerbox is gone, restarting
> 2015-03-08 20:49:32 [1] [0] INFO: Received (and handled?) 0 requests in 0
> seconds (-nan per second)
> 2015-03-08 20:49:32 [1] [0] INFO: Kannel smsbox terminating.
> 2015-03-08 20:49:32 [1] [8] DEBUG: Thread 8
> (gw/heartbeat.c:heartbeat_thread) terminates.
> 2015-03-08 20:49:32 [1] [0] DEBUG: Waiting for 2
> (gwlib/http.c:server_thread) to terminate
> 
> Took the kannel.conf from
> http://www.kannel.org/download/1.5.0/gateway-1.5.0/gw/smskannel.conf and
> only changed the 127.0.0.1 to 192.168.59.103 (docker's), also exposed ports.
> What could be wrong?
> 
> 2015-03-08 2:29 GMT+02:00 Tim Akinbo notifications@github.com:
> 
> > There are two issues here:
> > 1. You either need to build this image first or download it from
> >    docker hub. You can easily get the image from docker hub by running: docker
> >    pull takinbo/kannel and then replace every instance of the image name
> >    (kannel) with takinbo/kannel. E.g. docker run --rm -t -i --name
> >    bearerbox --hostname bearerbox --volume /opt/kannel/etc/:/etc/kannel
> >    --volume /opt/kannel/log:/var/log/kannel --volume
> >    /opt/kannel/spool:/var/spool/kannel takinbo/kannel bearerbox -v 0
> >    /etc/kannel/kannel.conf
> > 2. You will need to map an existing directory containing your
> >    kannel.conf file to the /etc/kannel directory on the container. I have used
> >    /opt/kannel in my example.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/takinbo/docker-kannel/issues/2#issuecomment-77724927
> > .
> 
> ## 
> 
> Yaniv Oren
> _Email:_ oren432@gmail.com
> _Phone:_ 972 508 612502
> _Site:_ www.Teach.Watch

## 

Yaniv Oren
_Email:_ oren432@gmail.com
_Phone:_ 972 508 612502
_Site:_ www.Teach.Watch

**Comment by takinbo** [comment]
I am familiar with the issue you're having. You need to name your bearerbox as the name it was linked as take a look at this [link](https://gist.github.com/takinbo/b181f03a95a969917a00).

Because the container was linked using the alias bearerbox (`--link bearerbox:bearerbox`) then your `bearerbox-host` should be the alias (bearerbox)

**Comment by oren4322** [comment]
Hi again, managed to run the bearbox & smsbox, used the smppsim as the smsc.
I'm sending the request to send the sms and receiving 0: Accepted for
delivery response.
But for some reason the sms is not sent.
I'm seeing these errors in smsbox log:

2015-03-21 20:20:52 [1] [3] DEBUG: Status: 202 Answer: <Sent.>
2015-03-21 20:20:52 [1] [3] DEBUG: Delayed reply - wait for bearerbox
2015-03-21 20:20:52 [1] [0] DEBUG: Got ACK (0) of
74f9cefe-db95-4b7d-aa99-f07395d32915
2015-03-21 20:20:52 [1] [0] DEBUG: HTTP: Resetting HTTPClient for
`192.168.59.3'.
2015-03-21 20:20:52 [1] [1] ERROR: Error reading from fd 24:
2015-03-21 20:20:52 [1] [1] ERROR: System error 104: Connection reset by
peer
2015-03-21 20:20:52 [1] [1] DEBUG: HTTP: Destroying HTTPClient area
0x7fe8d0000ad0.
Bearbox dosn't present any errors and seem to pass the message to smppsim,
smppsim shows this in log:

21 Assessing state of 1 messages in the OutboundQueue
21 Message:2 state=DELIVERED

Are you familiar with these warning or this situation?
TIA

2015-03-11 16:57 GMT+02:00 Tim Akinbo notifications@github.com:

> I am familiar with the issue you're having. You need to name your
> bearerbox as the name it was linked as take a look at this link
> https://gist.github.com/takinbo/b181f03a95a969917a00.
> 
> Because the container was linked using the alias bearerbox (--link
> bearerbox:bearerbox) then your bearerbox-host should be the alias
> (bearerbox)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/takinbo/docker-kannel/issues/2#issuecomment-78279533.

## 

Yaniv Oren
_Email:_ oren432@gmail.com
_Phone:_ 972 508 612502
_Site:_ www.Teach.Watch

**Comment by takinbo** [comment]
@oren4322 unfortunately I'm not familiar with this situation and it appears to have something to do with your configuration (either of kannel or smppsim) you might want to ask on kannel forums or mailing lists.

**Comment by oren4322** [comment]
Hi again,
Can you tell me if sending the sms requires a gsm modem? if it does, can it
use cellphone instead?
TIA

2015-03-22 18:08 GMT+02:00 Tim Akinbo notifications@github.com:

> Closed #2 https://github.com/takinbo/docker-kannel/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/takinbo/docker-kannel/issues/2#event-261626002.

## 

Yaniv Oren
_Email:_ oren432@gmail.com
_Phone:_ 972 508 612502
_Site:_ www.Teach.Watch
